# Parameters
[params]
    subtitle = "It's Dot Net ~~no wait~~"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/sflavelle"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://social.thegeneral.chat/@Splatsune"
        weight = 2 

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 


